name: CI

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2-beta
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Restore node_modules
        uses: actions/cache@v1
        id: node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}

      - name: Restore npm cache
        if: steps.node-modules.outputs.cache-hit != 'true'
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-cache-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            - ${{ runner.os }}-npm-cache-${{ hashFiles('package-lock.json') }}
            - ${{ runner.os }}-npm-cache-

      - name: npm install
        if: steps.node-modules.outputs.cache-hit != 'true'
        run: CYPRESS_INSTALL_BINARY=0 npm ci --prefer-offline --no-audit

      - run: npm run lint:quiet

  prettier:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2-beta
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Restore node_modules
        uses: actions/cache@v1
        id: node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}

      - name: Restore npm cache
        if: steps.node-modules.outputs.cache-hit != 'true'
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-cache-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            - ${{ runner.os }}-npm-cache-${{ hashFiles('package-lock.json') }}
            - ${{ runner.os }}-npm-cache-

      - name: npm install
        if: steps.node-modules.outputs.cache-hit != 'true'
        run: CYPRESS_INSTALL_BINARY=0 npm ci --prefer-offline --no-audit

      - run: npm run prettier:check

  check-langs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2-beta
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Restore node_modules
        uses: actions/cache@v1
        id: node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}

      - name: Restore npm cache
        if: steps.node-modules.outputs.cache-hit != 'true'
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-cache-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            - ${{ runner.os }}-npm-cache-${{ hashFiles('package-lock.json') }}
            - ${{ runner.os }}-npm-cache-

      - name: npm install
        if: steps.node-modules.outputs.cache-hit != 'true'
        run: CYPRESS_INSTALL_BINARY=0 npm ci --prefer-offline --no-audit

      - run: ./scripts/check_translations.sh

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2-beta
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Restore node_modules
        uses: actions/cache@v1
        id: node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}

      - name: Restore npm cache
        if: steps.node-modules.outputs.cache-hit != 'true'
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-cache-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            - ${{ runner.os }}-npm-cache-${{ hashFiles('package-lock.json') }}
            - ${{ runner.os }}-npm-cache-

      - name: npm install
        if: steps.node-modules.outputs.cache-hit != 'true'
        run: CYPRESS_INSTALL_BINARY=0 npm ci --prefer-offline --no-audit

      - name: Restore .next cache
        uses: actions/cache@v1
        id: next-cache
        with:
          path: .next/cache
          key: ${{ runner.os }}-next-cache-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-next-cache-${{ github.sha }}
            ${{ runner.os }}-next-cache-

      - run: npm run build:updates
      - run: npm run build:next
      - run: npm run build:server

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2-beta
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Restore node_modules
        uses: actions/cache@v1
        id: node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}

      - name: Restore npm cache
        if: steps.node-modules.outputs.cache-hit != 'true'
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-cache-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            - ${{ runner.os }}-npm-cache-${{ hashFiles('package-lock.json') }}
            - ${{ runner.os }}-npm-cache-

      - name: npm install
        if: steps.node-modules.outputs.cache-hit != 'true'
        run: CYPRESS_INSTALL_BINARY=0 npm ci --prefer-offline --no-audit

      - run: npm run test:jest
